### ISSUE TITLE
How to enable topic Tree? if settings.topicTreeEnabled is true: TypeError: this.callToCallbacks is not a function

### ISSUE THREAD

**Issue by easingthemes** [cedalo/management-center#71]
v2.5
If topicTreeEnabled is enabled: 
https://github.com/cedalo/management-center/blob/release/2.5/backend/src/settings/SettingsManager.js#L21

Undefined function is called.

**Comment by easingthemes** [comment]
Works fine in 2.5.9
